import test from 'node:test';import assert from 'node:assert/strict';import {validateBuilding,initialHazards,findRoute,compareId,comparePath}from '../dist/core.js';import {sampleBuilding as sample} from '../dist/sample.js';import {readFileSync} from 'node:fs';
const fresh=()=>({d:validateBuilding(sample),s:initialHazards(sample)});
test('all five official sample scenarios',()=>{
 const {d,s}=fresh();assert.deepEqual(findRoute(d,'R1',s),{status:'found',exit:'E1',cost:'7',path:['R1','C1','C2','E1'],edges:['L01','L02','L03']});
 const blocked=initialHazards(d);blocked.blocked_nodes.add('C2');assert.deepEqual(findRoute(d,'R1',blocked),{status:'found',exit:'E2',cost:'11',path:['R1','C1','C3','C4','E2'],edges:['L01','L08','L06','L07']});
 const closed=initialHazards(d);closed.closed_exits.add('E1');closed.closed_exits.add('E2');assert.equal(findRoute(d,'R1',closed).status,'noRoute');
 assert.deepEqual(findRoute(d,'R2',initialHazards(d)),{status:'found',exit:'E2',cost:'7',path:['R2','C3','C4','E2'],edges:['L05','L06','L07']});
 const startBlocked=initialHazards(d);startBlocked.blocked_nodes.add('R1');assert.equal(findRoute(d,'R1',startBlocked).status,'blockedStart');
});
test('bundled default matches downloadable official sample and includes every corridor',()=>{assert.deepEqual(sample,JSON.parse(readFileSync(new URL('../dist/building.json',import.meta.url),'utf8')));assert.equal(sample.building,'East Annex - Practice Building');assert.equal(sample.nodes.length,8);assert.equal(sample.edges.length,9);const state=initialHazards(sample);state.closed_exits.add('E1');assert.deepEqual(findRoute(sample,'R1',state).path,['R1','C1','C2','C4','E2']);assert.equal(findRoute(sample,'R1',state).cost,'10');state.blocked_edges.add('L08');state.blocked_nodes.add('C2');assert.deepEqual(findRoute(sample,'R1',state).path,['R1','R2','C3','C4','E2']);assert.equal(findRoute(sample,'R1',state).cost,'11');});
const n=(id,type='junction')=>({id,label:id,type,x:0,y:0});const graph=(nodes,edges)=>validateBuilding({building:'Test',nodes,edges:edges.map(([from,to,cost],i)=>({id:'e'+i,from,to,cost})),initial_state:{blocked_nodes:[],blocked_edges:[],closed_exits:[]}});
test('tie chooses exit ID before path sequence, then node sequence',()=>{const d=graph([n('S'),n('A'),n('B'),n('E2','exit'),n('E1','exit')],[['S','A',1],['S','B',1],['A','E2',1],['B','E1',1],['A','E1',1]]);assert.deepEqual(findRoute(d,'S',initialHazards(d)).path,['S','A','E1']);d.edges.reverse();assert.deepEqual(findRoute(d,'S',initialHazards(d)).path,['S','A','E1']);});
test('closed exit excluded even as an intermediate; blocked edge only removes connection',()=>{const d=graph([n('S'),n('X','exit'),n('Y','exit')],[['S','X',1],['X','Y',1],['S','Y',9]]),s=initialHazards(d);s.closed_exits.add('X');assert.equal(findRoute(d,'S',s).cost,'9');s.blocked_edges.add('e2');assert.equal(findRoute(d,'S',s).status,'noRoute');});
test('disconnected valid graph, no start and original hazards reset',()=>{const d=graph([n('S'),n('A'),n('E','exit')],[['S','A',2]]);assert.equal(findRoute(d,'S',initialHazards(d)).status,'noRoute');assert.equal(findRoute(d,null,initialHazards(d)).status,'selectStart');d.initial_state.blocked_nodes=['A'];const s=initialHazards(d);s.blocked_nodes.clear();assert.deepEqual([...initialHazards(d).blocked_nodes],['A']);});
test('exact large route costs',()=>{const d=graph([n('S'),n('A'),n('E','exit')],[['S','A',Number.MAX_SAFE_INTEGER],['A','E',2]]);assert.equal(findRoute(d,'S',initialHazards(d)).cost,'9007199254740993');});
test('malformed inputs rejected; case-sensitive IDs and negative coordinates accepted',()=>{for(const mutation of [d=>delete d.building,d=>d.nodes[0].x='1',d=>d.nodes[0].x=Infinity,d=>d.nodes[0].type='hall',d=>d.nodes[0].id=d.nodes[1].id,d=>d.edges[0].cost=0,d=>d.edges[0].cost=1.5,d=>d.edges[0].to='missing',d=>d.edges[0].to=d.edges[0].from,d=>d.edges[0].id=d.edges[1].id,d=>d.edges.push({...d.edges[0],id:'another',from:d.edges[0].to,to:d.edges[0].from}),d=>d.initial_state.closed_exits=['R1'],d=>d.initial_state.blocked_nodes=['E1'],d=>d.initial_state.blocked_edges=['missing'],d=>d.initial_state.blocked_nodes=['R1','R1'],d=>delete d.initial_state.closed_exits,d=>d.nodes=d.nodes.filter(n=>n.type!=='exit')]){const d=structuredClone(sample);mutation(d);assert.throws(()=>validateBuilding(d));}assert.doesNotThrow(()=>graph([n('s'),{...n('S','exit'),x:-5}],[['s','S',1]]));});
// Independent exhaustive simple-path oracle for small random graphs.
function brute(d,start,s){if(s.blocked_nodes.has(start))return{status:'blockedStart'};const out=[];function visit(id,path,edges,cost){const node=d.nodes.find(n=>n.id===id);if(node.type==='exit')out.push({status:'found',exit:id,path:[...path],edges:[...edges],cost:cost.toString()});for(const e of d.edges){const next=e.from===id?e.to:e.to===id?e.from:null;if(next!==null&&!path.includes(next)&&!s.blocked_nodes.has(next)&&!s.closed_exits.has(next)&&!s.blocked_edges.has(e.id))visit(next,[...path,next],[...edges,e.id],cost+BigInt(e.cost));}}visit(start,[start],[],0n);out.sort((a,b)=>BigInt(a.cost)<BigInt(b.cost)?-1:BigInt(a.cost)>BigInt(b.cost)?1:compareId(a.exit,b.exit)||comparePath(a.path,b.path));return out[0]??{status:'noRoute'};}
test('500 seeded random hazard graphs match exhaustive path oracle',()=>{let seed=1729;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};for(let trial=0;trial<500;trial++){const nodes=[n('S','room'),n('B'),n('A'),n('a'),n('E2','exit'),n('E1','exit')],edges=[];for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++)if(random()<.42)edges.push([nodes[i].id,nodes[j].id,1+Math.floor(random()*5)]);if(!edges.length)edges.push(['S','B',1]);const d=graph(nodes,edges),s=initialHazards(d);for(const node of nodes)if(random()<.2)s[node.type==='exit'?'closed_exits':'blocked_nodes'].add(node.id);for(const e of d.edges)if(random()<.2)s.blocked_edges.add(e.id);assert.deepEqual(findRoute(d,'S',s),brute(d,'S',s));}});
